#!/bin/bash
##########################################################
#     Automatically generated by the PandA framework     #
##########################################################

# Synthesis script for COMPONENT: main

#configuration
. /opt/Xilinx/Vivado/2020.1/settings64.sh >& /dev/null; 

# STEP: vivado_flow
vivado -mode batch -nojournal -nolog -source HLS_output//Synthesis/vivado_flow/vivado.tcl


